[package]
name = "logjangler-consumers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
logjangler-core = { path = "../logjangler-core" }
